### ISSUE TITLE
Testcontainers test fail in GitHub Action

### ISSUE THREAD

**Issue by mpeki** [mpeki/dod#212]
When running a docker-compose testcontainers test I see the error below:
```
[ntainers-wait-0] .c.w.i.InternalCommandPortListeningCheck : An exception while executing the internal check: Container.ExecResult(exitCode=137, stdout=, stderr=/bin/sh: /bin/bash: not found
    /bin/sh: /bin/bash: not found
    /bin/sh: /bin/bash: not found
    /bin/sh: /bin/bash: not found
    /bin/sh: /bin/bash: not found
...
haracterFlowTest > initializationError FAILED
    java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container to become healthy
        at org.rnorth.ducttape.timeouts.Timeouts.callFuture(Timeouts.java:68)
        at org.rnorth.ducttape.timeouts.Timeouts.doWithTimeout(Timeouts.java:60)
        at org.testcontainers.containers.wait.strategy.WaitAllStrategy.waitUntilReady(WaitAllStrategy.java:54)
        at org.testcontainers.containers.DockerComposeContainer.waitUntilServiceStarted(DockerComposeContainer.java:316)
        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
        at org.testcontainers.containers.DockerComposeContainer.waitUntilServiceStarted(DockerComposeContainer.java:290)
        at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:191)
        at dk.pekilidi.integration.CharacterFlowTest.startup(CharacterFlowTest.java:51)

        Caused by:
        org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container to become healthy
            at app//org.testcontainers.containers.wait.strategy.DockerHealthcheckWaitStrategy.waitUntilReady(DockerHealthcheckWaitStrategy.java:25)
            at app//org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
            at app//org.testcontainers.containers.wait.strategy.WaitAllStrategy.waitUntilNestedStrategiesAreReady(WaitAllStrategy.java:66)
            at app//org.testcontainers.containers.wait.strategy.WaitAllStrategy.lambda$waitUntilReady$0(WaitAllStrategy.java:58)
            at java.base@17.0.7/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
            at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
            at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
            at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
```
This test runs locally.

This was first seen after an update of testcontainers 1.17.6 -> 1.18.0, but downgrading didn't not work.

**Comment by mpeki** [comment]
Added logConsumer to testcontainers - lets see if anything is output on Github...

**Comment by mpeki** [comment]
next I'll try to add some robustness to container startup

**Comment by mpeki** [comment]
... added logging shows this on github:
```
STDOUT: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'changeRequestController' defined in file [/app/classes/dk/pekilidi/dod/changerequest/ChangeRequestController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'changeRequestService': Unsatisfied dependency expressed through field 'characterService': Error creating bean with name 'characterService': Unsatisfied dependency expressed through field 'ruleService': Error creating bean with name 'droolsService': Unsatisfied dependency expressed through field 'kieContainer': Error creating bean with name 'getKieContainer' defined in class path resource [dk/pekilidi/dod/rules/DroolsConfiguration.class]: Failed to instantiate [org.kie.api.runtime.KieContainer]: Factory method 'getKieContainer' threw exception with message: You're trying to compile a Drools ass...
```
Which means that:
`implementation "org.drools:drools-mvel:${droolsVersion}"`
has to be added as an dependency - problem didn't show locally because I did build a new docker image when running testcontainers tests - added `test_backend` alias which does this.
